export const Countries = {
    Afghanistan: 'AF', Albania: 'AL', Algeria: 'DZ', AmericanSamoa: 'AS', Andorra: 'AD', Angola: 'AO', Anguilla: 'AI', Antarctica: 'AQ', Argentina: 'AR', Armenia: 'AM', Aruba: 'AW', Australia: 'AU', Austria: 'AT', Azerbaijan: 'AZ',
    Bahamas: 'BS', Bahrain: 'BH', Bangladesh: 'BD', Barbados: 'BB', Belarus: 'BY', Belgium: 'BE', Belize: 'BZ', Benin: 'BJ', Bermuda: 'BM', Bhutan: 'BT', Botswana: 'BW', Brazil: 'BR', Bulgaria: 'BG', Burundi: 'BI',
    Cambodia: 'KH', Cameroon: 'CM', Canada: 'CA', Chad: 'TD', Chile: 'CL', China: 'CN', Colombia: 'CO', Comoros: 'KM', Congo: 'CG', Croatia: 'HR', Cuba: 'CU', Cyprus: 'CY',
    Denmark: 'DK', Djibouti: 'DJ', Dominica: 'DM',
    Ecuador: 'EC', Egypt: 'EG', Eritrea: 'ER', Estonia: 'EE', Ethiopia: 'ET',
    Fiji: 'FJ', Finland: 'FI', France: 'FR',
    Gabon: 'GA', Gambia: 'GM', Georgia: 'GE', Germany: 'DE', Ghana: 'GH', Gibraltar: 'GI', Greece: 'GR', Greenland: 'GL', Grenada: 'GD', Guadeloupe: 'GP', Guam: 'GU', Guatemala: 'GT', Guernsey: 'GG', Guinea: 'GN', Guyana: 'GY',
    Haiti: 'HT', Honduras: 'HN', HongKong: 'HK', Hungary: 'HU',
    Iceland: 'IS', India: 'IN', Indonesia: 'ID', Iraq: 'IQ', Ireland: 'IE', Israel: 'IL', Italy: 'IT',
    Jamaica: 'JM', Japan: 'JP', Jersey: 'JE', Jordan: 'JO',
    Kazakhstan: 'KZ', Kenya: 'KE', Kiribati: 'KI', Kuwait: 'KW', Kyrgyzstan: 'KG',
    Latvia: 'LV', Lebanon: 'LB', Lesotho: 'LS', Liberia: 'LR', Libya: 'LY', Liechtenstein: 'LI', Lithuania: 'LT', Luxembourg: 'LU',
    Macao: 'MO', Madagascar: 'MG', Malawi: 'MW', Malaysia: 'MY', Maldives: 'MV', Mali: 'ML', Malta: 'MT', Martinique: 'MQ', Mauritania: 'MR', Mauritius: 'MU', Mayotte: 'YT', Mexico: 'MX', Monaco: 'MC', Mongolia: 'MN', Montenegro: 'ME', Montserrat: 'MS', Morocco: 'MA', Mozambique: 'MZ', Myanmar: 'MM',
    Namibia: 'NA', Nauru: 'NR', Nepal: 'NP', Netherlands: 'NL', Nicaragua: 'NI', Niger: 'NE', Nigeria: 'NG', Niue: 'NU', Norway: 'NO',
    Oman: 'OM',
    Pakistan: 'PK', Palau: 'PW', Panama: 'PA', Paraguay: 'PY', Peru: 'PE', Philippines: 'PH', Pitcairn: 'PN', Poland: 'PL', Portugal: 'PT',
    Qatar: 'QA',
    Romania: 'RO', RussianFederation: 'RU', Rwanda: 'RW', Samoa: 'WS',
    Senegal: 'SN', Serbia: 'RS', Seychelles: 'SC', Singapore: 'SG', Slovakia: 'SK', Slovenia: 'SI', Somalia: 'SO', Spain: 'ES', Sudan: 'SD', Suriname: 'SR', Swaziland: 'SZ', Sweden: 'SE', Switzerland: 'CH', SyrianArabRepublic: 'SY',
    Tajikistan: 'TJ', Thailand: 'TH', TimorLeste: 'TL', Togo: 'TG', Tokelau: 'TK', Tonga: 'TO', Tunisia: 'TN', Turkey: 'TR', Turkmenistan: 'TM', Tuvalu: 'TV',
    Uganda: 'UG', Ukraine: 'UA', UnitedArabEmirates: 'AE', UnitedKingdom: 'GB', UnitedStates: 'US', Uruguay: 'UY', Uzbekistan: 'UZ',
    Vanuatu: 'VU', VietNam: 'VN',
    Yemen: 'YE',
    Zambia: 'ZM', Zimbabwe: 'ZW',
};
